#!/bin/sh

# AUTOSTART
# Set wallpaper
$HOME/library/system/configs/arch_setup/scripts &

# Start compositor
picom &

# Start polybar
$HOME/.config/polybar/launch.sh &

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# BSPWM CONFIGURATION
# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Border and gap
bspc config border-width		2
bspc config window_gap			12

#Colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# Window rules
bspc rule -a Chromium desktop='^2'

# Other settings
bspc config focus_folowws_pointer true
